import React from 'react';
import { Link } from 'react-router-dom';
import { Globe } from 'lucide-react';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100">
      {/* Header */}
      <div className="border-b border-zinc-800 bg-zinc-900">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
          <Link to="/" className="flex items-center gap-2">
            <div className="flex size-8 items-center justify-center rounded-lg bg-indigo-600 text-white">
              <Globe className="size-4" />
            </div>
            <span className="text-xl font-bold text-white">UptimeGuard</span>
          </Link>
          <Link to="/login" className="text-sm text-zinc-400 hover:text-white">
            Back to Login
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="mx-auto max-w-4xl px-6 py-12">
        <h1 className="mb-2 text-3xl font-bold text-white">Privacy Policy</h1>
        <p className="mb-8 text-sm text-zinc-500">Last updated: August 22, 2026</p>

        <div className="space-y-8 text-zinc-300 leading-relaxed">
          <section>
            <p className="mb-4 text-zinc-400 italic">
              UptimeGuard is a personal project. This privacy policy explains how I collect, use, and protect your information when you use the service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">1. Information I Collect</h2>
            <ul className="ml-6 list-disc space-y-2">
              <li><strong className="text-white">Account Information:</strong> When you sign up, I collect your name and email address. If you sign in with Google, your email and profile information are obtained through Google OAuth.</li>
              <li><strong className="text-white">Monitor Data:</strong> URLs and configuration details for the websites you choose to monitor.</li>
              <li><strong className="text-white">Usage Data:</strong> Uptime check results, response times, and incident logs generated by the monitoring service.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">2. How I Use Your Information</h2>
            <ul className="ml-6 list-disc space-y-2">
              <li>To provide and maintain the monitoring service.</li>
              <li>To send you uptime and downtime notifications you have configured.</li>
              <li>To authenticate your account and prevent unauthorized access.</li>
              <li>To improve the service.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">3. Data Storage &amp; Security</h2>
            <p>
              Your data is stored on secure servers. I take reasonable measures to protect your personal information, but no method of electronic transmission or storage is 100% secure. I cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">4. Data Sharing</h2>
            <p>
              I do not sell, trade, or otherwise transfer your personal information to third parties. Your data is only used to provide the UptimeGuard service. The only third-party service involved is Google OAuth for authentication, which is governed by Google's own privacy policy.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">5. Data Retention</h2>
            <p>
              I retain your account information and monitor data for as long as your account is active. You may delete your account at any time, which will remove your personal data from the system.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">6. Cookies</h2>
            <p>
              UptimeGuard uses session cookies for authentication purposes only. These are essential for the service to function and are not used for tracking or advertising.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">7. Your Rights</h2>
            <p>
              You have the right to access, update, or delete your personal information at any time through the Settings page. If you have any questions or requests regarding your data, please contact me.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">8. Changes to This Policy</h2>
            <p>
              I may update this privacy policy from time to time. Changes will be reflected on this page with an updated date. Continued use of the service after changes constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">9. Contact</h2>
            <p>
              If you have any questions about this privacy policy, please reach out through the UptimeGuard support channels.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
